// Geographic seeds for query fan-out (Tennessee). Broad coverage beats a short
// list: most facility sites only surface for a city-scoped query.
export const NY_MARKETS = [
  'Nashville TN',
  'Franklin TN',
  'Brentwood TN',
  'Murfreesboro TN',
  'Smyrna TN',
  'La Vergne TN',
  'Hendersonville TN',
  'Gallatin TN',
  'Mount Juliet TN',
  'Lebanon TN',
  'Spring Hill TN',
  'Columbia TN',
  'Nolensville TN',
  'Thompson\'s Station TN',
  'Goodlettsville TN',
  'Madison TN',
  'Antioch TN',
  'Dickson TN',
  'Fairview TN',
  'White House TN',
  'Portland TN',
  'Springfield TN',
  'Clarksville TN',
  'Oak Grove TN',
  'Memphis TN',
  'Germantown TN',
  'Collierville TN',
  'Bartlett TN',
  'Cordova TN',
  'Millington TN',
  'Lakeland TN',
  'Arlington TN',
  'Jackson TN',
  'Dyersburg TN',
  'Union City TN',
  'Martin TN',
  'Brownsville TN',
  'Covington TN',
  'Knoxville TN',
  'Farragut TN',
  'Maryville TN',
  'Alcoa TN',
  'Oak Ridge TN',
  'Sevierville TN',
  'Pigeon Forge TN',
  'Gatlinburg TN',
  'Morristown TN',
  'Clinton TN',
  'Powell TN',
  'Lenoir City TN',
  'Loudon TN',
  'Seymour TN',
  'Jefferson City TN',
  'Dandridge TN',
  'Newport TN',
  'Chattanooga TN',
  'Cleveland TN',
  'East Ridge TN',
  'Red Bank TN',
  'Hixson TN',
  'Collegedale TN',
  'Ooltewah TN',
  'Soddy-Daisy TN',
  'Signal Mountain TN',
  'Dayton TN',
  'Athens TN',
  'McMinnville TN',
  'Tullahoma TN',
  'Manchester TN',
  'Shelbyville TN',
  'Winchester TN',
  'Lynchburg TN',
  'Lawrenceburg TN',
  'Pulaski TN',
  'Lewisburg TN',
  'Fayetteville TN',
  'Johnson City TN',
  'Kingsport TN',
  'Bristol TN',
  'Greeneville TN',
  'Elizabethton TN',
  'Erwin TN',
  'Jonesborough TN',
  'Cookeville TN',
  'Crossville TN',
  'Livingston TN',
  'Sparta TN',
];

// Region labels used only for progress reporting / notes.
export const NY_REGIONS = [
  "Nashville / Middle Tennessee",
  "Clarksville",
  "Memphis / West Tennessee",
  "Knoxville / East Tennessee",
  "Chattanooga / Southeast Tennessee",
  "South Central Tennessee",
  "Tri-Cities / Northeast Tennessee",
  "Upper Cumberland"
];
