// Geographic seeds for query fan-out (Florida). Broad coverage beats a short
// list: most facility sites only surface for a city-scoped query.
export const NY_MARKETS = [
  'Miami FL',
  'Miami Beach FL',
  'Miami Gardens FL',
  'Hialeah FL',
  'Coral Gables FL',
  'Doral FL',
  'Kendall FL',
  'Homestead FL',
  'Aventura FL',
  'North Miami FL',
  'North Miami Beach FL',
  'Cutler Bay FL',
  'Palmetto Bay FL',
  'Pinecrest FL',
  'Sweetwater FL',
  'Miami Lakes FL',
  'Key Biscayne FL',
  'Fort Lauderdale FL',
  'Hollywood FL',
  'Pembroke Pines FL',
  'Miramar FL',
  'Coral Springs FL',
  'Pompano Beach FL',
  'Davie FL',
  'Plantation FL',
  'Sunrise FL',
  'Deerfield Beach FL',
  'Weston FL',
  'Tamarac FL',
  'Margate FL',
  'Coconut Creek FL',
  'Lauderhill FL',
  'Hallandale Beach FL',
  'Cooper City FL',
  'Parkland FL',
  'West Palm Beach FL',
  'Boca Raton FL',
  'Delray Beach FL',
  'Boynton Beach FL',
  'Jupiter FL',
  'Palm Beach Gardens FL',
  'Wellington FL',
  'Lake Worth FL',
  'Royal Palm Beach FL',
  'Greenacres FL',
  'Palm Beach FL',
  'Riviera Beach FL',
  'Juno Beach FL',
  'Port St. Lucie FL',
  'Stuart FL',
  'Vero Beach FL',
  'Jensen Beach FL',
  'Fort Pierce FL',
  'Sebastian FL',
  'Palm City FL',
  'Naples FL',
  'Bonita Springs FL',
  'Estero FL',
  'Fort Myers FL',
  'Cape Coral FL',
  'Marco Island FL',
  'Lehigh Acres FL',
  'Punta Gorda FL',
  'Port Charlotte FL',
  'Sarasota FL',
  'Bradenton FL',
  'Venice FL',
  'Lakewood Ranch FL',
  'Palmetto FL',
  'North Port FL',
  'Osprey FL',
  'Nokomis FL',
  'Tampa FL',
  'St. Petersburg FL',
  'Clearwater FL',
  'Brandon FL',
  'Riverview FL',
  'Wesley Chapel FL',
  'Palm Harbor FL',
  'Largo FL',
  'Pinellas Park FL',
  'Dunedin FL',
  'Safety Harbor FL',
  'Oldsmar FL',
  'Land O Lakes FL',
  'Lutz FL',
  'Valrico FL',
  'Apollo Beach FL',
  'New Port Richey FL',
  'Trinity FL',
  'Tarpon Springs FL',
  'Seminole FL',
  'Lakeland FL',
  'Winter Haven FL',
  'Plant City FL',
  'Bartow FL',
  'Auburndale FL',
  'Davenport FL',
  'Haines City FL',
  'Orlando FL',
  'Winter Park FL',
  'Kissimmee FL',
  'Altamonte Springs FL',
  'Sanford FL',
  'Lake Mary FL',
  'Oviedo FL',
  'Winter Garden FL',
  'Clermont FL',
  'Apopka FL',
  'Maitland FL',
  'Casselberry FL',
  'Longwood FL',
  'Ocoee FL',
  'Windermere FL',
  'St. Cloud FL',
  'Winter Springs FL',
  'Ocala FL',
  'The Villages FL',
  'Gainesville FL',
  'Lady Lake FL',
  'Leesburg FL',
  'Mount Dora FL',
  'Tavares FL',
  'Eustis FL',
  'Jacksonville FL',
  'Orange Park FL',
  'St. Augustine FL',
  'Ponte Vedra Beach FL',
  'Palm Coast FL',
  'Fleming Island FL',
  'Fernandina Beach FL',
  'St. Johns FL',
  'Daytona Beach FL',
  'Port Orange FL',
  'Deltona FL',
  'DeLand FL',
  'New Smyrna Beach FL',
  'Ormond Beach FL',
  'Melbourne FL',
  'Palm Bay FL',
  'Titusville FL',
  'Cocoa FL',
  'Cocoa Beach FL',
  'Rockledge FL',
  'Merritt Island FL',
  'Satellite Beach FL',
  'Tallahassee FL',
  'Panama City FL',
  'Panama City Beach FL',
  'Pensacola FL',
  'Fort Walton Beach FL',
  'Destin FL',
  'Navarre FL',
  'Niceville FL',
  'Crestview FL',
  'Gulf Breeze FL',
  'Key West FL',
  'Key Largo FL',
  'Marathon FL',
  'Islamorada FL',
];

// Region labels used only for progress reporting / notes.
export const NY_REGIONS = [
  "Miami-Dade",
  "Broward",
  "Palm Beach",
  "Treasure Coast",
  "Southwest Florida",
  "Sarasota-Manatee",
  "Tampa Bay",
  "Polk",
  "Orlando Metro",
  "North Central",
  "Northeast Florida",
  "Space Coast",
  "Panhandle",
  "Florida Keys"
];
