// Geographic seeds for query fan-out (Texas). Broad coverage beats a short
// list: most facility sites only surface for a city-scoped query.
export const NY_MARKETS = [
  'Dallas TX',
  'Fort Worth TX',
  'Arlington TX',
  'Plano TX',
  'Garland TX',
  'Irving TX',
  'Frisco TX',
  'McKinney TX',
  'Grand Prairie TX',
  'Denton TX',
  'Mesquite TX',
  'Carrollton TX',
  'Richardson TX',
  'Lewisville TX',
  'Allen TX',
  'Flower Mound TX',
  'North Richland Hills TX',
  'Mansfield TX',
  'Euless TX',
  'Grapevine TX',
  'Bedford TX',
  'Cedar Hill TX',
  'Wylie TX',
  'Keller TX',
  'Coppell TX',
  'Rowlett TX',
  'DeSoto TX',
  'Little Elm TX',
  'Prosper TX',
  'Southlake TX',
  'Colleyville TX',
  'The Colony TX',
  'Farmers Branch TX',
  'Rockwall TX',
  'Burleson TX',
  'Haltom City TX',
  'Hurst TX',
  'Duncanville TX',
  'Lancaster TX',
  'Waxahachie TX',
  'Midlothian TX',
  'Weatherford TX',
  'Cleburne TX',
  'Houston TX',
  'Pasadena TX',
  'Pearland TX',
  'Sugar Land TX',
  'The Woodlands TX',
  'League City TX',
  'Baytown TX',
  'Conroe TX',
  'Missouri City TX',
  'Katy TX',
  'Spring TX',
  'Cypress TX',
  'Friendswood TX',
  'Deer Park TX',
  'La Porte TX',
  'Texas City TX',
  'Galveston TX',
  'Rosenberg TX',
  'Humble TX',
  'Tomball TX',
  'Stafford TX',
  'Bellaire TX',
  'Kingwood TX',
  'Atascocita TX',
  'Richmond TX',
  'Fulshear TX',
  'Channelview TX',
  'Austin TX',
  'Round Rock TX',
  'Cedar Park TX',
  'Georgetown TX',
  'Pflugerville TX',
  'San Marcos TX',
  'Leander TX',
  'Kyle TX',
  'Buda TX',
  'Hutto TX',
  'Lakeway TX',
  'Dripping Springs TX',
  'Bastrop TX',
  'San Antonio TX',
  'New Braunfels TX',
  'Schertz TX',
  'Seguin TX',
  'Cibolo TX',
  'Universal City TX',
  'Boerne TX',
  'Converse TX',
  'Live Oak TX',
  'Selma TX',
  'Helotes TX',
  'El Paso TX',
  'Socorro TX',
  'Horizon City TX',
  'McAllen TX',
  'Brownsville TX',
  'Harlingen TX',
  'Edinburg TX',
  'Pharr TX',
  'Mission TX',
  'Weslaco TX',
  'San Benito TX',
  'Mercedes TX',
  'Corpus Christi TX',
  'Portland TX',
  'Kingsville TX',
  'Robstown TX',
  'Beaumont TX',
  'Port Arthur TX',
  'Orange TX',
  'Nederland TX',
  'Lumberton TX',
  'Waco TX',
  'Temple TX',
  'Killeen TX',
  'Belton TX',
  'Harker Heights TX',
  'College Station TX',
  'Bryan TX',
  'Huntsville TX',
  'Brenham TX',
  'Lubbock TX',
  'Amarillo TX',
  'Midland TX',
  'Odessa TX',
  'San Angelo TX',
  'Abilene TX',
  'Big Spring TX',
  'Wichita Falls TX',
  'Plainview TX',
  'Tyler TX',
  'Longview TX',
  'Marshall TX',
  'Nacogdoches TX',
  'Lufkin TX',
  'Texarkana TX',
  'Paris TX',
  'Sherman TX',
  'Denison TX',
  'Greenville TX',
  'Palestine TX',
  'Laredo TX',
  'Del Rio TX',
  'Eagle Pass TX',
  'Uvalde TX',
  'Victoria TX',
  'Fredericksburg TX',
  'Kerrville TX',
  'Marble Falls TX',
];

// Region labels used only for progress reporting / notes.
export const NY_REGIONS = [
  "Dallas-Fort Worth",
  "Houston Metro",
  "Austin Metro",
  "San Antonio Metro",
  "El Paso",
  "Rio Grande Valley",
  "Coastal Bend",
  "Southeast Texas",
  "Central Texas",
  "West Texas & Panhandle",
  "East Texas",
  "South Texas",
  "Hill Country"
];
