// Per-state configuration. Everything geographic lives here so a new state is
// a data change, not a code change: add an entry and the whole pipeline -
// discovery fan-out, city parsing, address parsing and the location gate -
// follows it.
import { NY_MARKETS } from './geo.js';

// Two-label public suffixes are handled in search.js; this is only the
// state-owned government space that is out of scope per the brief.
const GOV = (code) => [/\.gov$/i, /\.mil$/i, new RegExp(`\\.${code.toLowerCase()}\\.us$`, 'i')];

const CA_MARKETS = [
  // Los Angeles County
  'Los Angeles CA', 'Long Beach CA', 'Glendale CA', 'Pasadena CA', 'Torrance CA',
  'Santa Monica CA', 'Burbank CA', 'El Segundo CA', 'Culver City CA', 'Inglewood CA',
  'Redondo Beach CA', 'Manhattan Beach CA', 'Hermosa Beach CA', 'Carson CA', 'Cerritos CA',
  'Downey CA', 'Norwalk CA', 'Whittier CA', 'Lakewood CA', 'Compton CA',
  'Santa Clarita CA', 'Valencia CA', 'Lancaster CA', 'Palmdale CA', 'Woodland Hills CA',
  'Sherman Oaks CA', 'Van Nuys CA', 'Northridge CA', 'Encino CA', 'Studio City CA',
  'West Covina CA', 'Pomona CA', 'Arcadia CA', 'Monrovia CA', 'Alhambra CA',
  'El Monte CA', 'Rosemead CA', 'Diamond Bar CA', 'Walnut CA', 'San Gabriel CA',
  'Hawthorne CA', 'Gardena CA', 'Bellflower CA', 'Paramount CA', 'Montebello CA',
  // Orange County
  'Anaheim CA', 'Irvine CA', 'Santa Ana CA', 'Huntington Beach CA', 'Newport Beach CA',
  'Costa Mesa CA', 'Fullerton CA', 'Orange CA', 'Tustin CA', 'Mission Viejo CA',
  'Laguna Niguel CA', 'Lake Forest CA', 'Yorba Linda CA', 'Brea CA', 'Buena Park CA',
  'Garden Grove CA', 'Westminster CA', 'Fountain Valley CA', 'Aliso Viejo CA',
  'San Clemente CA', 'Dana Point CA', 'Rancho Santa Margarita CA', 'Cypress CA', 'Placentia CA',
  // San Diego County
  'San Diego CA', 'Carlsbad CA', 'Encinitas CA', 'Oceanside CA', 'Vista CA',
  'Escondido CA', 'San Marcos CA', 'Chula Vista CA', 'La Jolla CA', 'Poway CA',
  'El Cajon CA', 'La Mesa CA', 'Santee CA', 'Coronado CA', 'Del Mar CA',
  'Rancho Bernardo CA', 'Solana Beach CA', 'National City CA', 'Imperial Beach CA',
  // Inland Empire - Riverside & San Bernardino
  'Riverside CA', 'San Bernardino CA', 'Ontario CA', 'Rancho Cucamonga CA', 'Fontana CA',
  'Corona CA', 'Temecula CA', 'Murrieta CA', 'Moreno Valley CA', 'Redlands CA',
  'Chino CA', 'Chino Hills CA', 'Upland CA', 'Claremont CA', 'Hemet CA',
  'Menifee CA', 'Perris CA', 'Victorville CA', 'Apple Valley CA', 'Hesperia CA',
  'Palm Springs CA', 'Palm Desert CA', 'La Quinta CA', 'Indio CA', 'Rancho Mirage CA',
  'Eastvale CA', 'Jurupa Valley CA', 'Yucaipa CA', 'Colton CA', 'Rialto CA',
  // Ventura & Santa Barbara
  'Ventura CA', 'Oxnard CA', 'Thousand Oaks CA', 'Simi Valley CA', 'Camarillo CA',
  'Westlake Village CA', 'Moorpark CA', 'Santa Barbara CA', 'Goleta CA', 'Carpinteria CA',
  'Santa Maria CA', 'Lompoc CA', 'Ojai CA',
  // Central Coast & Monterey Bay
  'San Luis Obispo CA', 'Paso Robles CA', 'Atascadero CA', 'Pismo Beach CA', 'Arroyo Grande CA',
  'Santa Cruz CA', 'Watsonville CA', 'Scotts Valley CA', 'Monterey CA', 'Salinas CA',
  'Seaside CA', 'Marina CA', 'Carmel CA', 'Hollister CA', 'Gilroy CA', 'Morgan Hill CA',
  // Bay Area - San Francisco & Peninsula
  'San Francisco CA', 'Daly City CA', 'South San Francisco CA', 'San Mateo CA', 'Burlingame CA',
  'Redwood City CA', 'Menlo Park CA', 'Palo Alto CA', 'Foster City CA', 'San Bruno CA',
  'Millbrae CA', 'Belmont CA', 'San Carlos CA', 'Half Moon Bay CA', 'Pacifica CA',
  // Silicon Valley
  'San Jose CA', 'Santa Clara CA', 'Sunnyvale CA', 'Mountain View CA', 'Cupertino CA',
  'Milpitas CA', 'Campbell CA', 'Los Gatos CA', 'Saratoga CA', 'Los Altos CA',
  'Fremont CA', 'Newark CA', 'Union City CA',
  // East Bay
  'Oakland CA', 'Berkeley CA', 'Alameda CA', 'San Leandro CA', 'Hayward CA',
  'Pleasanton CA', 'Dublin CA', 'Livermore CA', 'San Ramon CA', 'Danville CA',
  'Walnut Creek CA', 'Concord CA', 'Pleasant Hill CA', 'Martinez CA', 'Antioch CA',
  'Brentwood CA', 'Pittsburg CA', 'Richmond CA', 'El Cerrito CA', 'Castro Valley CA',
  'Lafayette CA', 'Orinda CA', 'Moraga CA', 'Emeryville CA',
  // North Bay
  'Santa Rosa CA', 'Petaluma CA', 'Novato CA', 'San Rafael CA', 'Mill Valley CA',
  'Napa CA', 'Vallejo CA', 'Fairfield CA', 'Vacaville CA', 'Benicia CA',
  'Sonoma CA', 'Rohnert Park CA', 'Windsor CA', 'Healdsburg CA', 'Corte Madera CA',
  // Sacramento region
  'Sacramento CA', 'Roseville CA', 'Folsom CA', 'Elk Grove CA', 'Rocklin CA',
  'Citrus Heights CA', 'Rancho Cordova CA', 'Davis CA', 'Woodland CA', 'El Dorado Hills CA',
  'Lincoln CA', 'Auburn CA', 'Granite Bay CA', 'West Sacramento CA', 'Yuba City CA',
  // Central Valley - Stockton, Modesto, Fresno, Bakersfield
  'Stockton CA', 'Modesto CA', 'Tracy CA', 'Manteca CA', 'Lodi CA', 'Turlock CA',
  'Ceres CA', 'Ripon CA', 'Fresno CA', 'Clovis CA', 'Visalia CA', 'Tulare CA',
  'Hanford CA', 'Madera CA', 'Merced CA', 'Los Banos CA', 'Bakersfield CA',
  'Delano CA', 'Porterville CA', 'Ridgecrest CA',
  // North Coast & Far Northern California
  'Eureka CA', 'Arcata CA', 'Ukiah CA', 'Fort Bragg CA', 'Redding CA',
  'Chico CA', 'Paradise CA', 'Oroville CA', 'Red Bluff CA', 'Susanville CA',
  'Grass Valley CA', 'Nevada City CA', 'Truckee CA', 'South Lake Tahoe CA', 'Placerville CA',
  'Marysville CA', 'Anderson CA', 'Willows CA',
];

// Municipalities used to pick the real city out of an address line.
const CA_PLACES = new Set(
  CA_MARKETS.map((m) => m.replace(/\s+CA$/, '').toLowerCase()).concat([
    'north hollywood', 'canoga park', 'reseda', 'tarzana', 'chatsworth', 'granada hills',
    'playa vista', 'marina del rey', 'venice', 'brentwood heights', 'westwood', 'hollywood',
    'san pedro', 'wilmington', 'harbor city', 'rolling hills', 'palos verdes',
    'rancho palos verdes', 'la canada flintridge', 'sierra madre', 'temple city',
    'south pasadena', 'san marino', 'la verne', 'san dimas', 'glendora', 'azusa', 'covina',
    'baldwin park', 'la mirada', 'la habra', 'seal beach', 'los alamitos', 'stanton',
    'laguna beach', 'laguna hills', 'san juan capistrano', 'ladera ranch', 'coto de caza',
    'rancho penasquitos', 'carmel valley', 'mira mesa', 'clairemont', 'point loma',
    'pacific beach', 'ocean beach', 'lemon grove', 'spring valley', 'bonita', 'alpine',
    'ramona', 'fallbrook', 'temecula valley', 'wildomar', 'lake elsinore', 'canyon lake',
    'beaumont', 'banning', 'calimesa', 'loma linda', 'grand terrace', 'highland',
    'twentynine palms', 'yucca valley', 'barstow', 'adelanto', 'cathedral city',
    'desert hot springs', 'coachella', 'blythe', 'el centro', 'calexico', 'brawley',
    'agoura hills', 'calabasas', 'malibu', 'port hueneme', 'fillmore', 'santa paula',
    'goleta valley', 'buellton', 'solvang', 'grover beach', 'morro bay', 'nipomo',
    'aptos', 'capitola', 'felton', 'ben lomond', 'pacific grove', 'pebble beach',
    'king city', 'greenfield', 'soledad', 'san juan bautista', 'san benito',
    'brisbane', 'hillsborough', 'atherton', 'portola valley', 'woodside', 'east palo alto',
    'san anselmo', 'fairfax', 'larkspur', 'tiburon', 'sausalito', 'greenbrae',
    'american canyon', 'st helena', 'calistoga', 'yountville', 'dixon', 'rio vista',
    'suisun city', 'cotati', 'sebastopol', 'cloverdale', 'guerneville',
    'orangevale', 'fair oaks', 'carmichael', 'north highlands', 'antelope', 'galt',
    'loomis', 'penryn', 'newcastle', 'colfax', 'cameron park', 'shingle springs',
    'lathrop', 'escalon', 'oakdale', 'riverbank', 'patterson', 'newman', 'gustine',
    'atwater', 'livingston', 'chowchilla', 'kerman', 'sanger', 'reedley', 'selma',
    'kingsburg', 'dinuba', 'exeter', 'lindsay', 'shafter', 'wasco', 'taft',
    'tehachapi', 'california city', 'mcfarland', 'arvin', 'lamont',
    'mckinleyville', 'fortuna', 'crescent city', 'weaverville', 'mount shasta',
    'yreka', 'alturas', 'quincy', 'portola', 'colusa', 'orland', 'corning',
    'gridley', 'live oak', 'wheatland', 'rocklin hills', 'el dorado', 'jackson',
    'sonora', 'angels camp', 'mariposa', 'bishop', 'mammoth lakes',
  ]),
);


const FL_MARKETS = [
  'Miami FL', 'Miami Beach FL', 'Coral Gables FL', 'Hialeah FL', 'Doral FL', 'Kendall FL',
  'Fort Lauderdale FL', 'Hollywood FL', 'Pembroke Pines FL', 'Coral Springs FL', 'Plantation FL',
  'Sunrise FL', 'Davie FL', 'Weston FL', 'Boca Raton FL', 'Delray Beach FL', 'Boynton Beach FL',
  'West Palm Beach FL', 'Jupiter FL', 'Wellington FL', 'Palm Beach Gardens FL', 'Port St Lucie FL',
  'Stuart FL', 'Vero Beach FL', 'Naples FL', 'Bonita Springs FL', 'Fort Myers FL', 'Cape Coral FL',
  'Estero FL', 'Sarasota FL', 'Bradenton FL', 'Venice FL', 'Lakewood Ranch FL', 'Punta Gorda FL',
  'Tampa FL', 'St Petersburg FL', 'Clearwater FL', 'Brandon FL', 'Riverview FL', 'Wesley Chapel FL',
  'Lutz FL', 'Palm Harbor FL', 'Largo FL', 'Dunedin FL', 'Temple Terrace FL', 'Plant City FL',
  'Orlando FL', 'Winter Park FL', 'Winter Garden FL', 'Kissimmee FL', 'Altamonte Springs FL',
  'Lake Mary FL', 'Sanford FL', 'Oviedo FL', 'Clermont FL', 'Apopka FL', 'Ocoee FL', 'Celebration FL',
  'Jacksonville FL', 'Jacksonville Beach FL', 'Ponte Vedra FL', 'St Augustine FL', 'Orange Park FL',
  'Fleming Island FL', 'Fernandina Beach FL', 'Daytona Beach FL', 'Ormond Beach FL', 'Palm Coast FL',
  'Melbourne FL', 'Palm Bay FL', 'Viera FL', 'Cocoa FL', 'Titusville FL', 'Merritt Island FL',
  'Gainesville FL', 'Ocala FL', 'The Villages FL', 'Leesburg FL', 'Lady Lake FL',
  'Tallahassee FL', 'Panama City FL', 'Destin FL', 'Fort Walton Beach FL', 'Pensacola FL',
  'Niceville FL', 'Crestview FL', 'Santa Rosa Beach FL', 'Lakeland FL', 'Winter Haven FL',
  'Sebring FL', 'Key West FL', 'Marathon FL', 'Homestead FL', 'Miramar FL', 'Aventura FL',
];

const TN_MARKETS = [
  'Nashville TN', 'Franklin TN', 'Brentwood TN', 'Murfreesboro TN', 'Hendersonville TN',
  'Smyrna TN', 'Mount Juliet TN', 'Gallatin TN', 'Spring Hill TN', 'Lebanon TN', 'Nolensville TN',
  'Clarksville TN', 'Columbia TN', 'Dickson TN', 'Springfield TN', 'White House TN',
  'Memphis TN', 'Germantown TN', 'Collierville TN', 'Bartlett TN', 'Cordova TN', 'Arlington TN',
  'Millington TN', 'Jackson TN', 'Dyersburg TN', 'Union City TN', 'Martin TN',
  'Knoxville TN', 'Farragut TN', 'Maryville TN', 'Alcoa TN', 'Oak Ridge TN', 'Sevierville TN',
  'Pigeon Forge TN', 'Gatlinburg TN', 'Morristown TN', 'Jefferson City TN', 'Lenoir City TN',
  'Chattanooga TN', 'Cleveland TN', 'East Ridge TN', 'Hixson TN', 'Ooltewah TN', 'Signal Mountain TN',
  'Johnson City TN', 'Kingsport TN', 'Bristol TN', 'Elizabethton TN', 'Greeneville TN',
  'Cookeville TN', 'Crossville TN', 'McMinnville TN', 'Tullahoma TN', 'Shelbyville TN',
  'Manchester TN', 'Lawrenceburg TN', 'Pulaski TN', 'Fayetteville TN', 'Winchester TN',
  'Sparta TN', 'Livingston TN', 'Athens TN', 'Sweetwater TN', 'Harriman TN', 'Kingston TN',
];


const TX_MARKETS = [
  // Houston metro
  'Houston TX', 'Katy TX', 'Sugar Land TX', 'Pearland TX', 'The Woodlands TX',
  'Spring TX', 'Cypress TX', 'Humble TX', 'Kingwood TX', 'Missouri City TX',
  'Friendswood TX', 'League City TX', 'Pasadena TX', 'Baytown TX', 'Conroe TX',
  'Richmond TX', 'Tomball TX', 'Stafford TX', 'Bellaire TX', 'Galveston TX',
  // Dallas-Fort Worth metroplex
  'Dallas TX', 'Fort Worth TX', 'Plano TX', 'Frisco TX', 'McKinney TX',
  'Allen TX', 'Richardson TX', 'Garland TX', 'Irving TX', 'Arlington TX',
  'Grapevine TX', 'Southlake TX', 'Colleyville TX', 'Keller TX', 'Coppell TX',
  'Carrollton TX', 'Lewisville TX', 'Flower Mound TX', 'Denton TX', 'Rockwall TX',
  'Mansfield TX', 'Grand Prairie TX', 'Mesquite TX', 'Wylie TX', 'Prosper TX',
  'Little Elm TX', 'The Colony TX', 'Euless TX', 'Bedford TX', 'North Richland Hills TX',
  'Addison TX', 'Farmers Branch TX', 'Duncanville TX', 'Cedar Hill TX', 'Waxahachie TX',
  // Austin metro
  'Austin TX', 'Round Rock TX', 'Cedar Park TX', 'Georgetown TX', 'Pflugerville TX',
  'Leander TX', 'Lakeway TX', 'Buda TX', 'Kyle TX', 'San Marcos TX', 'Bastrop TX',
  // San Antonio metro
  'San Antonio TX', 'New Braunfels TX', 'Schertz TX', 'Boerne TX', 'Converse TX',
  'Universal City TX', 'Seguin TX', 'Helotes TX', 'Cibolo TX',
  // Gulf Coast & South Texas
  'Corpus Christi TX', 'Victoria TX', 'Brownsville TX', 'McAllen TX', 'Harlingen TX',
  'Edinburg TX', 'Mission TX', 'Pharr TX', 'Laredo TX', 'Beaumont TX',
  'Port Arthur TX', 'Texas City TX', 'Lake Jackson TX',
  // West Texas & Panhandle
  'El Paso TX', 'Lubbock TX', 'Amarillo TX', 'Midland TX', 'Odessa TX',
  'San Angelo TX', 'Abilene TX', 'Big Spring TX', 'Plainview TX', 'Canyon TX',
  // East & Central Texas
  'Tyler TX', 'Longview TX', 'Waco TX', 'Temple TX', 'Killeen TX', 'Bryan TX',
  'College Station TX', 'Huntsville TX', 'Nacogdoches TX', 'Texarkana TX',
  'Sherman TX', 'Paris TX', 'Marshall TX', 'Lufkin TX', 'Brenham TX',
  'Wichita Falls TX', 'Copperas Cove TX', 'Harker Heights TX', 'Belton TX',
];


const PA_MARKETS = [
  // Philadelphia metro
  'Philadelphia PA', 'Bala Cynwyd PA', 'Ardmore PA', 'Bryn Mawr PA', 'Villanova PA',
  'Wayne PA', 'King of Prussia PA', 'Conshohocken PA', 'Plymouth Meeting PA', 'Norristown PA',
  'Blue Bell PA', 'Ambler PA', 'Lansdale PA', 'Horsham PA', 'Willow Grove PA',
  'Abington PA', 'Jenkintown PA', 'Huntingdon Valley PA', 'Newtown PA', 'Doylestown PA',
  'Warminster PA', 'Langhorne PA', 'Bensalem PA', 'Levittown PA', 'Yardley PA',
  'Media PA', 'Springfield PA', 'Broomall PA', 'Havertown PA', 'Drexel Hill PA',
  'Chester PA', 'West Chester PA', 'Exton PA', 'Malvern PA', 'Downingtown PA',
  'Phoenixville PA', 'Coatesville PA', 'Kennett Square PA', 'Chadds Ford PA',
  // Lehigh Valley & Poconos
  'Allentown PA', 'Bethlehem PA', 'Easton PA', 'Emmaus PA', 'Whitehall PA',
  'Nazareth PA', 'Quakertown PA', 'Stroudsburg PA', 'East Stroudsburg PA', 'Mount Pocono PA',
  // Harrisburg & Central
  'Harrisburg PA', 'Hershey PA', 'Camp Hill PA', 'Mechanicsburg PA', 'Carlisle PA',
  'Lemoyne PA', 'Hummelstown PA', 'Palmyra PA', 'Lebanon PA', 'Chambersburg PA',
  'Gettysburg PA', 'Shippensburg PA', 'Waynesboro PA',
  // Lancaster & York
  'Lancaster PA', 'Lititz PA', 'Ephrata PA', 'Elizabethtown PA', 'Columbia PA',
  'York PA', 'Hanover PA', 'Red Lion PA', 'Dover PA',
  // Reading & Berks
  'Reading PA', 'Wyomissing PA', 'Sinking Spring PA', 'Boyertown PA', 'Pottstown PA',
  // Pittsburgh metro
  'Pittsburgh PA', 'Monroeville PA', 'Wexford PA', 'Cranberry Township PA', 'Sewickley PA',
  'Bethel Park PA', 'Mount Lebanon PA', 'Upper St Clair PA', 'Canonsburg PA', 'McMurray PA',
  'Robinson Township PA', 'Moon Township PA', 'Greensburg PA', 'Murrysville PA',
  'Butler PA', 'Beaver PA', 'Aliquippa PA', 'Washington PA', 'Uniontown PA',
  'New Kensington PA', 'Latrobe PA', 'Indiana PA', 'Johnstown PA', 'Somerset PA',
  // Northeast PA
  'Scranton PA', 'Wilkes-Barre PA', 'Pittston PA', 'Clarks Summit PA', 'Dunmore PA',
  'Hazleton PA', 'Kingston PA', 'Nanticoke PA', 'Honesdale PA', 'Carbondale PA',
  // Northwest & North Central
  'Erie PA', 'Meadville PA', 'Warren PA', 'Oil City PA', 'Franklin PA',
  'Sharon PA', 'Hermitage PA', 'New Castle PA', 'Grove City PA', 'DuBois PA',
  'State College PA', 'Bellefonte PA', 'Altoona PA', 'Huntingdon PA', 'Lewistown PA',
  'Williamsport PA', 'Lock Haven PA', 'Bloomsburg PA', 'Danville PA', 'Sunbury PA',
  'Selinsgrove PA', 'Lewisburg PA', 'Towanda PA', 'Sayre PA', 'Bradford PA',
  // Additional Pennsylvania municipalities: statewide coverage means the small
  // boroughs too, not just the metros.
  'Bristol PA', 'Morrisville PA', 'Perkasie PA', 'Souderton PA', 'Telford PA',
  'Collegeville PA', 'Royersford PA', 'Spring City PA', 'Limerick PA', 'Trappe PA',
  'Hatboro PA', 'Warrington PA', 'Chalfont PA', 'New Hope PA', 'Richboro PA',
  'Southampton PA', 'Feasterville PA', 'Holland PA', 'Washington Crossing PA',
  'Glenside PA', 'Elkins Park PA', 'Cheltenham PA', 'Wyncote PA', 'Flourtown PA',
  'Lafayette Hill PA', 'Gladwyne PA', 'Narberth PA', 'Wynnewood PA', 'Berwyn PA',
  'Paoli PA', 'Devon PA', 'Frazer PA', 'Chesterbrook PA', 'Newtown Square PA',
  'Glen Mills PA', 'Aston PA', 'Swarthmore PA', 'Ridley Park PA', 'Folsom PA',
  'Lansdowne PA', 'Yeadon PA', 'Darby PA', 'Clifton Heights PA', 'Marcus Hook PA',
  'Oxford PA', 'Avondale PA', 'Parkesburg PA', 'Honey Brook PA', 'Elverson PA',
  'Macungie PA', 'Trexlertown PA', 'Catasauqua PA', 'Northampton PA', 'Bath PA',
  'Palmerton PA', 'Lehighton PA', 'Jim Thorpe PA', 'Tamaqua PA', 'Pottsville PA',
  'Schuylkill Haven PA', 'Frackville PA', 'Shenandoah PA', 'Minersville PA',
  'New Cumberland PA', 'Enola PA', 'Dillsburg PA', 'Marysville PA', 'Duncannon PA',
  'Newport PA', 'Millersburg PA', 'Halifax PA', 'Middletown PA', 'Highspire PA',
  'Manheim PA', 'Mount Joy PA', 'Strasburg PA', 'New Holland PA', 'Denver PA',
  'Akron PA', 'Willow Street PA', 'Quarryville PA', 'Millersville PA', 'Marietta PA',
  'Shrewsbury PA', 'Stewartstown PA', 'Spring Grove PA', 'New Freedom PA', 'Glen Rock PA',
  'Mohnton PA', 'Shillington PA', 'Kutztown PA', 'Fleetwood PA', 'Birdsboro PA',
  'Hamburg PA', 'Bernville PA', 'Womelsdorf PA', 'Myerstown PA', 'Annville PA',
  'McCandless PA', 'Shaler PA', 'Fox Chapel PA', 'Oakmont PA', 'Plum PA',
  'Penn Hills PA', 'North Huntingdon PA', 'Irwin PA', 'Jeannette PA', 'Export PA',
  'Delmont PA', 'Ligonier PA', 'Mount Pleasant PA', 'Scottdale PA', 'Connellsville PA',
  'Peters Township PA', 'Bridgeville PA', 'Carnegie PA', 'Coraopolis PA', 'Imperial PA',
  'Mars PA', 'Zelienople PA', 'Evans City PA', 'Gibsonia PA', 'Allison Park PA',
  'Ambridge PA', 'Monaca PA', 'Chippewa PA', 'Ellwood City PA', 'Slippery Rock PA',
  'Kittanning PA', 'Ford City PA', 'Vandergrift PA', 'Apollo PA', 'Blairsville PA',
  'Moosic PA', 'Old Forge PA', 'Archbald PA', 'Jessup PA', 'Olyphant PA',
  'Plains PA', 'West Pittston PA', 'Shavertown PA', 'Dallas PA', 'Tunkhannock PA',
  'Stroud Township PA', 'Brodheadsville PA', 'Milford PA', 'Matamoras PA',
  'Edinboro PA', 'Girard PA', 'North East PA', 'Fairview PA', 'Harborcreek PA',
  'Corry PA', 'Union City PA', 'Titusville PA', 'Clarion PA', 'Brookville PA',
  'St Marys PA', 'Ridgway PA', 'Kane PA', 'Emporium PA', 'Coudersport PA',
  'Boalsburg PA', 'Port Matilda PA', 'Philipsburg PA', 'Clearfield PA', 'Punxsutawney PA',
  'Tyrone PA', 'Hollidaysburg PA', 'Duncansville PA', 'Martinsburg PA', 'Bedford PA',
  'Everett PA', 'Mount Union PA', 'Mifflintown PA', 'Burnham PA', 'Milroy PA',
  'Montoursville PA', 'Muncy PA', 'Jersey Shore PA', 'South Williamsport PA',
  'Berwick PA', 'Shamokin PA', 'Mount Carmel PA', 'Milton PA', 'Watsontown PA',
  'Mifflinburg PA', 'Northumberland PA', 'Elysburg PA', 'Catawissa PA',
  'Athens PA', 'Wyalusing PA', 'Wellsboro PA', 'Mansfield PA', 'Galeton PA',
];

const MI_MARKETS = [
  // Metro Detroit
  'Detroit MI', 'Dearborn MI', 'Livonia MI', 'Novi MI', 'Northville MI',
  'Plymouth MI', 'Canton MI', 'Westland MI', 'Farmington Hills MI', 'Southfield MI',
  'Royal Oak MI', 'Birmingham MI', 'Troy MI', 'Rochester Hills MI', 'Auburn Hills MI',
  'Bloomfield Hills MI', 'West Bloomfield MI', 'Sterling Heights MI', 'Warren MI',
  'Shelby Township MI', 'Clinton Township MI', 'Macomb MI', 'Chesterfield MI',
  'Grosse Pointe MI', 'St Clair Shores MI', 'Taylor MI', 'Wyandotte MI', 'Trenton MI',
  'Pontiac MI', 'Waterford MI', 'Clarkston MI', 'Lake Orion MI', 'Commerce Township MI',
  'Wixom MI', 'Milford MI', 'South Lyon MI', 'Brighton MI', 'Howell MI',
  // Ann Arbor & Lansing
  'Ann Arbor MI', 'Ypsilanti MI', 'Saline MI', 'Chelsea MI', 'Dexter MI',
  'Lansing MI', 'East Lansing MI', 'Okemos MI', 'Holt MI', 'Grand Ledge MI',
  // West Michigan
  'Grand Rapids MI', 'Wyoming MI', 'Kentwood MI', 'Grandville MI', 'Walker MI',
  'Hudsonville MI', 'Jenison MI', 'Holland MI', 'Zeeland MI', 'Grand Haven MI',
  'Muskegon MI', 'Norton Shores MI', 'Rockford MI', 'Cedar Springs MI', 'Ada MI',
  'Caledonia MI', 'Byron Center MI', 'Allendale MI',
  // Southwest & South Central
  'Kalamazoo MI', 'Portage MI', 'Battle Creek MI', 'Jackson MI', 'Marshall MI',
  'St Joseph MI', 'Benton Harbor MI', 'Niles MI', 'Three Rivers MI', 'Sturgis MI',
  'Adrian MI', 'Monroe MI', 'Tecumseh MI', 'Coldwater MI', 'Hillsdale MI',
  // Mid & Northern Michigan
  'Flint MI', 'Grand Blanc MI', 'Fenton MI', 'Davison MI', 'Saginaw MI',
  'Bay City MI', 'Midland MI', 'Mount Pleasant MI', 'Alma MI', 'Owosso MI',
  'Traverse City MI', 'Petoskey MI', 'Cadillac MI', 'Gaylord MI', 'Alpena MI',
  'Big Rapids MI', 'Ludington MI', 'Manistee MI', 'Charlevoix MI',
  // Upper Peninsula
  'Marquette MI', 'Escanaba MI', 'Sault Ste Marie MI', 'Houghton MI', 'Iron Mountain MI',
  // Additional Michigan municipalities for full statewide reach.
  'Berkley MI', 'Ferndale MI', 'Oak Park MI', 'Huntington Woods MI', 'Clawson MI',
  'Beverly Hills MI', 'Franklin MI', 'Orchard Lake MI', 'Walled Lake MI', 'Wolverine Lake MI',
  'White Lake MI', 'Highland MI', 'Hartland MI', 'New Hudson MI', 'Wixom MI',
  'Redford MI', 'Garden City MI', 'Romulus MI', 'Belleville MI', 'Van Buren MI',
  'Allen Park MI', 'Lincoln Park MI', 'Southgate MI', 'Riverview MI', 'Woodhaven MI',
  'Grosse Ile MI', 'Flat Rock MI', 'Utica MI', 'Washington Township MI', 'Romeo MI',
  'Armada MI', 'Richmond MI', 'New Baltimore MI', 'Harrison Township MI',
  'Roseville MI', 'Eastpointe MI', 'Fraser MI', 'Center Line MI', 'Madison Heights MI',
  'Hamburg MI', 'Pinckney MI', 'Whitmore Lake MI', 'Milan MI', 'Manchester MI',
  'Haslett MI', 'Williamston MI', 'Mason MI', 'DeWitt MI', 'St Johns MI',
  'Charlotte MI', 'Eaton Rapids MI', 'Potterville MI', 'Perry MI', 'Laingsburg MI',
  'Comstock Park MI', 'Belmont MI', 'Lowell MI', 'Ionia MI', 'Greenville MI',
  'Sparta MI', 'Coopersville MI', 'Spring Lake MI', 'Fruitport MI', 'Whitehall MI',
  'Montague MI', 'Newaygo MI', 'Fremont MI', 'Hastings MI', 'Wayland MI',
  'Middleville MI', 'Rockford MI', 'Cedar Springs MI', 'Ada MI', 'Caledonia MI',
  'Mattawan MI', 'Paw Paw MI', 'Plainwell MI', 'Otsego MI', 'Richland MI',
  'Vicksburg MI', 'Schoolcraft MI', 'South Haven MI', 'Stevensville MI', 'Bridgman MI',
  'Buchanan MI', 'Dowagiac MI', 'Edwardsburg MI', 'Cassopolis MI', 'Allegan MI',
  'Burton MI', 'Flushing MI', 'Swartz Creek MI', 'Linden MI', 'Goodrich MI',
  'Clio MI', 'Lapeer MI', 'Imlay City MI', 'Almont MI', 'Marlette MI',
  'Frankenmuth MI', 'Freeland MI', 'Auburn MI', 'Essexville MI', 'Caro MI',
  'Vassar MI', 'Sandusky MI', 'Bad Axe MI', 'Port Huron MI', 'Marysville MI',
  'St Clair MI', 'Algonac MI', 'Yale MI', 'Croswell MI',
  'Shepherd MI', 'Ithaca MI', 'St Louis MI', 'Clare MI', 'Harrison MI',
  'Houghton Lake MI', 'Roscommon MI', 'West Branch MI', 'Standish MI', 'Tawas City MI',
  'Acme MI', 'Williamsburg MI', 'Suttons Bay MI', 'Elk Rapids MI', 'Kalkaska MI',
  'Boyne City MI', 'East Jordan MI', 'Harbor Springs MI', 'Cheboygan MI', 'Grayling MI',
  'Reed City MI', 'Evart MI', 'Scottville MI', 'Baldwin MI', 'Lake City MI',
  'Negaunee MI', 'Ishpeming MI', 'Gladstone MI', 'Menominee MI', 'Calumet MI',
  'Hancock MI', 'Munising MI', 'Newberry MI', 'St Ignace MI', 'Manistique MI',
];

const WA_MARKETS = [
  // Seattle / Eastside
  'Seattle WA', 'Bellevue WA', 'Redmond WA', 'Kirkland WA', 'Renton WA', 'Kent WA',
  'Auburn WA', 'Federal Way WA', 'Tukwila WA', 'Burien WA', 'Des Moines WA', 'SeaTac WA',
  'Mercer Island WA', 'Issaquah WA', 'Sammamish WA', 'Snoqualmie WA', 'North Bend WA',
  'Maple Valley WA', 'Covington WA', 'Kenmore WA', 'Woodinville WA', 'Duvall WA',
  'Bothell WA', 'Mountlake Terrace WA', 'Shoreline WA',
  // Tacoma / South Sound
  'Tacoma WA', 'Puyallup WA', 'Lakewood WA', 'University Place WA', 'Fife WA',
  'Sumner WA', 'Bonney Lake WA', 'Gig Harbor WA', 'Olympia WA', 'Lacey WA', 'Tumwater WA',
  'Yelm WA', 'Shelton WA', 'Port Orchard WA', 'Bremerton WA', 'Poulsbo WA',
  'Silverdale WA', 'Bainbridge Island WA',
  // Everett / Snohomish County
  'Everett WA', 'Lynnwood WA', 'Edmonds WA', 'Mukilteo WA', 'Mill Creek WA',
  'Marysville WA', 'Monroe WA', 'Snohomish WA', 'Arlington WA', 'Lake Stevens WA',
  'Stanwood WA',
  // Southwest WA
  'Vancouver WA', 'Camas WA', 'Battle Ground WA', 'Ridgefield WA', 'Washougal WA',
  'Longview WA', 'Kelso WA',
  // Eastern WA
  'Spokane WA', 'Spokane Valley WA', 'Cheney WA', 'Liberty Lake WA', 'Airway Heights WA',
  'Yakima WA', 'Union Gap WA', 'Wenatchee WA', 'East Wenatchee WA', 'Ellensburg WA',
  'Moses Lake WA', 'Kennewick WA', 'Richland WA', 'Pasco WA', 'Walla Walla WA', 'Pullman WA',
  'Colville WA', 'Newport WA',
  // North Sound / Whatcom
  'Bellingham WA', 'Ferndale WA', 'Mount Vernon WA', 'Burlington WA', 'Anacortes WA',
  'Oak Harbor WA', 'Sedro-Woolley WA',
  // Olympic Peninsula & coast
  'Port Angeles WA', 'Sequim WA', 'Port Townsend WA', 'Aberdeen WA', 'Hoquiam WA',
  'Centralia WA', 'Chehalis WA',
];

const AZ_MARKETS = [
  // Phoenix metro
  'Phoenix AZ', 'Scottsdale AZ', 'Tempe AZ', 'Mesa AZ', 'Chandler AZ', 'Gilbert AZ',
  'Glendale AZ', 'Peoria AZ', 'Surprise AZ', 'Avondale AZ', 'Goodyear AZ', 'Buckeye AZ',
  'Queen Creek AZ', 'Paradise Valley AZ', 'Fountain Hills AZ', 'Cave Creek AZ',
  'Carefree AZ', 'Anthem AZ', 'El Mirage AZ', 'Tolleson AZ', 'Litchfield Park AZ',
  'Apache Junction AZ', 'Casa Grande AZ', 'Maricopa AZ', 'Sun City AZ', 'Sun City West AZ',
  'Laveen AZ', 'Ahwatukee AZ', 'Youngtown AZ', 'Wickenburg AZ',
  // Tucson metro
  'Tucson AZ', 'Oro Valley AZ', 'Marana AZ', 'Sahuarita AZ', 'Green Valley AZ',
  'South Tucson AZ', 'Vail AZ',
  // Northern Arizona
  'Flagstaff AZ', 'Sedona AZ', 'Prescott AZ', 'Prescott Valley AZ', 'Cottonwood AZ',
  'Camp Verde AZ', 'Williams AZ', 'Page AZ', 'Chino Valley AZ',
  // Southern & western Arizona
  'Yuma AZ', 'Lake Havasu City AZ', 'Bullhead City AZ', 'Kingman AZ', 'Nogales AZ',
  'Sierra Vista AZ', 'Douglas AZ', 'Safford AZ', 'Globe AZ', 'Payson AZ', 'Show Low AZ',
  'Winslow AZ', 'Holbrook AZ', 'Benson AZ', 'Florence AZ', 'Eloy AZ',
];

const NV_MARKETS = [
  // Las Vegas metro
  'Las Vegas NV', 'Henderson NV', 'North Las Vegas NV', 'Paradise NV', 'Spring Valley NV',
  'Enterprise NV', 'Summerlin NV', 'Sunrise Manor NV', 'Boulder City NV', 'Mesquite NV',
  'Pahrump NV', 'Laughlin NV',
  // Reno / Carson City area
  'Reno NV', 'Sparks NV', 'Carson City NV', 'Gardnerville NV', 'Minden NV',
  'Incline Village NV', 'Fernley NV', 'Fallon NV', 'Dayton NV',
  // Rural Nevada
  'Elko NV', 'Winnemucca NV', 'Ely NV', 'Yerington NV', 'Pioche NV', 'Tonopah NV',
  'Battle Mountain NV',
];

const OR_MARKETS = [
  // Portland metro
  'Portland OR', 'Beaverton OR', 'Hillsboro OR', 'Gresham OR', 'Tigard OR',
  'Lake Oswego OR', 'Tualatin OR', 'West Linn OR', 'Wilsonville OR', 'Oregon City OR',
  'Milwaukie OR', 'Happy Valley OR', 'Sherwood OR', 'Forest Grove OR', 'Cornelius OR',
  'Troutdale OR', 'Fairview OR', 'Wood Village OR', 'Sandy OR', 'Damascus OR',
  'King City OR', 'Durham OR', 'Hillsboro OR',
  // Willamette Valley
  'Newberg OR', 'McMinnville OR', 'Salem OR', 'Keizer OR', 'Albany OR', 'Corvallis OR',
  'Eugene OR', 'Springfield OR', 'Woodburn OR', 'Silverton OR', 'Dallas OR',
  'Independence OR', 'Monmouth OR', 'Canby OR', 'Molalla OR', 'Estacada OR',
  'Lebanon OR', 'Sweet Home OR', 'Junction City OR', 'Cottage Grove OR', 'Stayton OR',
  // Central & Southern Oregon
  'Bend OR', 'Redmond OR', 'Medford OR', 'Ashland OR', 'Grants Pass OR', 'Roseburg OR',
  'Klamath Falls OR', 'Prineville OR', 'Sisters OR', 'Talent OR', 'Phoenix OR',
  'Central Point OR',
  // Coast
  'Coos Bay OR', 'North Bend OR', 'Astoria OR', 'Seaside OR', 'Warrenton OR',
  'Lincoln City OR', 'Newport OR', 'Tillamook OR', 'Florence OR', 'Brookings OR',
  'Hood River OR',
  // Eastern Oregon
  'Pendleton OR', 'La Grande OR', 'Ontario OR', 'Baker City OR', 'The Dalles OR',
];

// Markets double as the municipality whitelist; `extra` adds neighbourhoods and
// smaller towns that appear in addresses but are not worth querying separately.
const placeSet = (markets, extra = []) =>
  new Set(markets.map((m) => m.replace(/\s+[A-Z]{2}$/, '').toLowerCase()).concat(extra));

export const STATES = {
  NY: {
    code: 'NY',
    name: 'New York',
    // Matches "NY" or the spelled-out name in an address.
    stateRe: /(?:NY|New York)/,
    zipRe: /\bNY\s+1\d{4}\b/,
    zipBare: /^1\d{4}$/,
    areaCodes: /\(?(212|315|332|347|516|518|585|607|631|646|680|716|718|838|845|914|917|929|934)\)?[)\s.-]{1,3}\d{3}[\s.-]?\d{4}/,
    mentionRe: /\bNew York (?:State|City)\b/i,
    markets: NY_MARKETS,
    places: null, // supplied by extract.js NY_PLACES for backwards compatibility
    gov: GOV('NY').concat([/\.state\.ny\.us$/i]),
    statewide: [
      'indoor pickleball facilities New York State directory',
      'USTA Eastern indoor tennis facilities New York',
      'indoor sports complex New York State list',
      'New York volleyball clubs indoor facility list',
      'New York squash clubs list',
      'best indoor pickleball courts upstate New York',
      'sportsplex New York State',
    ],
  },
  CA: {
    code: 'CA',
    name: 'California',
    stateRe: /(?:CA|California|Calif\.?)/,
    // California ZIPs are 90000-96199.
    zipRe: /\b(?:CA|California)\s+9[0-6]\d{3}\b/,
    // California ZIPs run 90000-96199; anything else contradicts the state token.
    zipBare: /^9[0-6]\d{3}$/,
    areaCodes:
      /\(?(209|213|279|310|323|341|350|408|415|424|442|510|530|559|562|619|626|628|650|657|661|669|707|714|747|760|764|805|818|820|831|837|840|858|909|916|925|949|951)\)?[)\s.-]{1,3}\d{3}[\s.-]?\d{4}/,
    mentionRe: /\b(?:Southern|Northern|Central) California\b|\bCalifornia\b/i,
    markets: CA_MARKETS,
    // Dense markets worth all 31 query angles. Everywhere else gets the ten
    // highest-yield ones, which is what keeps total query volume inside what
    // the search engines will serve before they rate-limit collectively.
    majorMarkets: [
      'Los Angeles CA', 'Long Beach CA', 'Glendale CA', 'Pasadena CA', 'Torrance CA',
      'Santa Monica CA', 'Burbank CA', 'Culver City CA', 'Santa Clarita CA', 'Woodland Hills CA',
      'Sherman Oaks CA', 'Van Nuys CA', 'Northridge CA', 'West Covina CA', 'Pomona CA',
      'Anaheim CA', 'Irvine CA', 'Santa Ana CA', 'Huntington Beach CA', 'Newport Beach CA',
      'Costa Mesa CA', 'Fullerton CA', 'Orange CA', 'Mission Viejo CA', 'Garden Grove CA',
      'San Diego CA', 'Carlsbad CA', 'Encinitas CA', 'Oceanside CA', 'Escondido CA',
      'Chula Vista CA', 'La Jolla CA', 'Poway CA', 'El Cajon CA',
      'Riverside CA', 'San Bernardino CA', 'Ontario CA', 'Rancho Cucamonga CA', 'Corona CA',
      'Temecula CA', 'Murrieta CA', 'Redlands CA', 'Chino Hills CA', 'Palm Desert CA',
      'Ventura CA', 'Oxnard CA', 'Thousand Oaks CA', 'Simi Valley CA', 'Santa Barbara CA',
      'San Luis Obispo CA', 'Santa Cruz CA', 'Monterey CA', 'Salinas CA',
      'San Francisco CA', 'San Mateo CA', 'Redwood City CA', 'Palo Alto CA', 'Menlo Park CA',
      'San Jose CA', 'Santa Clara CA', 'Sunnyvale CA', 'Mountain View CA', 'Cupertino CA',
      'Fremont CA', 'Los Gatos CA', 'Campbell CA',
      'Oakland CA', 'Berkeley CA', 'Alameda CA', 'Hayward CA', 'Pleasanton CA',
      'Dublin CA', 'Livermore CA', 'San Ramon CA', 'Walnut Creek CA', 'Concord CA',
      'Santa Rosa CA', 'Petaluma CA', 'San Rafael CA', 'Napa CA', 'Vallejo CA', 'Fairfield CA',
      'Sacramento CA', 'Roseville CA', 'Folsom CA', 'Elk Grove CA', 'Rocklin CA', 'Davis CA',
      'Stockton CA', 'Modesto CA', 'Tracy CA', 'Fresno CA', 'Clovis CA', 'Visalia CA',
      'Merced CA', 'Bakersfield CA', 'Redding CA', 'Chico CA', 'Eureka CA', 'Truckee CA',
    ],
    places: CA_PLACES,
    gov: GOV('CA'),
    statewide: [
      'indoor pickleball facilities California directory',
      'USTA Southern California indoor tennis facilities',
      'USTA Northern California indoor tennis clubs',
      'indoor sports complex California list',
      'California volleyball clubs indoor facility list',
      'California squash clubs list',
      'California badminton clubs list',
      'indoor padel clubs California',
      'best indoor pickleball courts Southern California',
      'best indoor pickleball courts Northern California',
      'sportsplex California',
      'California YMCA gymnasium court rental',
      'California multi-location indoor sports facility operator',
      'indoor basketball facility California list',
      'California futsal facilities indoor',
    ],
  },
  FL: {
    code: 'FL',
    name: 'Florida',
    stateRe: /(?:FL|Florida|Fla\.?)/,
    // Florida ZIPs run 32000-34999.
    zipRe: /\b(?:FL|Florida)\s+3[234]\d{3}\b/,
    zipBare: /^3[234]\d{3}$/,
    areaCodes:
      /\(?(239|305|321|352|386|407|448|561|656|689|727|754|772|786|813|850|863|904|941|954)\)?[)\s.-]{1,3}\d{3}[\s.-]?\d{4}/,
    mentionRe: /\b(?:South|Central|North) Florida\b|\bFlorida\b/i,
    markets: FL_MARKETS,
    places: placeSet(FL_MARKETS, [
      'south miami', 'north miami', 'north miami beach', 'miami lakes', 'miami gardens',
      'coconut grove', 'brickell', 'pinecrest', 'palmetto bay', 'cutler bay', 'sunny isles beach',
      'key biscayne', 'bal harbour', 'surfside', 'opa locka', 'hialeah gardens',
      'deerfield beach', 'pompano beach', 'oakland park', 'wilton manors', 'lauderhill',
      'tamarac', 'margate', 'coconut creek', 'parkland', 'cooper city', 'southwest ranches',
      'lake worth', 'greenacres', 'royal palm beach', 'palm beach', 'north palm beach',
      'tequesta', 'jensen beach', 'hobe sound', 'fort pierce', 'sebastian',
      'marco island', 'immokalee', 'lehigh acres', 'north fort myers', 'fort myers beach',
      'north port', 'englewood', 'nokomis', 'osprey', 'palmetto', 'ellenton', 'parrish',
      'safety harbor', 'oldsmar', 'seminole', 'pinellas park', 'st pete beach', 'tarpon springs',
      'new port richey', 'port richey', 'trinity', 'land o lakes', 'zephyrhills', 'valrico',
      'maitland', 'longwood', 'casselberry', 'winter springs', 'st cloud', 'davenport',
      'windermere', 'dr phillips', 'lake nona', 'mount dora', 'eustis', 'tavares',
      'neptune beach', 'atlantic beach', 'middleburg', 'green cove springs', 'nocatee',
      'port orange', 'new smyrna beach', 'deland', 'deltona', 'edgewater', 'flagler beach',
      'indialantic', 'satellite beach', 'rockledge', 'cape canaveral', 'alachua', 'newberry',
      'navarre', 'gulf breeze', 'milton', 'pace', 'panama city beach', 'marianna',
      'bartow', 'auburndale', 'haines city', 'lake wales', 'avon park', 'okeechobee',
      'islamorada', 'key largo',
    ]),
    gov: GOV('FL'),
    statewide: [
      'indoor pickleball facilities Florida directory',
      'USTA Florida indoor tennis facilities',
      'indoor sports complex Florida list',
      'Florida volleyball clubs indoor facility list',
      'indoor padel clubs Florida',
      'best indoor pickleball courts Florida',
      'sportsplex Florida',
      'Florida YMCA gymnasium court rental',
    ],
  },
  TN: {
    code: 'TN',
    name: 'Tennessee',
    stateRe: /(?:TN|Tennessee|Tenn\.?)/,
    // Tennessee ZIPs run 37000-38599.
    zipRe: /\b(?:TN|Tennessee)\s+3[78]\d{3}\b/,
    zipBare: /^3[78]\d{3}$/,
    areaCodes: /\(?(423|615|629|731|865|901|931)\)?[)\s.-]{1,3}\d{3}[\s.-]?\d{4}/,
    mentionRe: /\b(?:East|Middle|West) Tennessee\b|\bTennessee\b/i,
    markets: TN_MARKETS,
    places: placeSet(TN_MARKETS, [
      'antioch', 'bellevue', 'donelson', 'hermitage', 'madison', 'goodlettsville',
      'green hills', 'belle meade', 'berry hill', 'thompsons station', 'arrington',
      'fairview', 'ashland city', 'pleasant view', 'portland', 'la vergne',
      'oakland', 'lakeland', 'somerville', 'covington', 'brownsville',
      'powell', 'halls', 'karns', 'hardin valley', 'louisville', 'friendsville',
      'seymour', 'dandridge', 'newport', 'rogersville', 'church hill', 'jonesborough',
      'red bank', 'soddy daisy', 'collegedale', 'apison', 'lookout mountain',
      'algood', 'baxter', 'monterey', 'smithville', 'woodbury', 'lynchburg',
      'tellico village', 'loudon', 'clinton', 'norris', 'jacksboro',
    ]),
    gov: GOV('TN'),
    statewide: [
      'indoor pickleball facilities Tennessee directory',
      'USTA Southern indoor tennis facilities Tennessee',
      'indoor sports complex Tennessee list',
      'Tennessee volleyball clubs indoor facility list',
      'best indoor pickleball courts Tennessee',
      'sportsplex Tennessee',
      'Tennessee YMCA gymnasium court rental',
    ],
  },
  TX: {
    code: 'TX',
    name: 'Texas',
    stateRe: /(?:TX|Texas|Tex\.?)/,
    // Texas ZIPs run 75000-79999, plus the 885xx block around El Paso.
    zipRe: /\b(?:TX|Texas)\s+(?:7[5-9]\d{3}|885\d{2})\b/,
    zipBare: /^(?:7[5-9]\d{3}|885\d{2})$/,
    areaCodes:
      /\(?(210|214|254|281|325|346|361|409|430|432|469|512|682|713|726|737|806|817|830|832|903|915|936|940|945|956|972|979)\)?[)\s.-]{1,3}\d{3}[\s.-]?\d{4}/,
    mentionRe: /\b(?:East|West|North|South|Central) Texas\b|\bTexas\b/i,
    markets: TX_MARKETS,
    places: placeSet(TX_MARKETS, [
      'westchase', 'memorial', 'river oaks', 'montrose', 'heights', 'midtown',
      'clear lake', 'webster', 'seabrook', 'deer park', 'la porte', 'channelview',
      'atascocita', 'porter', 'magnolia', 'montgomery', 'willis', 'rosenberg',
      'fulshear', 'brookshire', 'santa fe', 'dickinson', 'alvin', 'angleton',
      'highland park', 'university park', 'preston hollow', 'oak lawn', 'deep ellum',
      'trophy club', 'roanoke', 'argyle', 'justin', 'haslet', 'saginaw', 'watauga',
      'hurst', 'crowley', 'burleson', 'midlothian', 'red oak', 'ennis', 'corsicana',
      'sachse', 'murphy', 'lucas', 'fairview', 'melissa', 'anna', 'princeton',
      'celina', 'aubrey', 'sanger', 'krum', 'ponder', 'forney', 'terrell',
      'westlake hills', 'rollingwood', 'bee cave', 'dripping springs', 'manor',
      'hutto', 'taylor', 'liberty hill', 'jarrell', 'elgin', 'lockhart',
      'alamo heights', 'stone oak', 'leon valley', 'live oak', 'selma', 'bulverde',
      'canyon lake', 'floresville', 'pleasanton', 'castroville', 'fair oaks ranch',
      'portland', 'rockport', 'kingsville', 'alice', 'weslaco', 'san benito',
      'los fresnos', 'rio grande city', 'eagle pass', 'del rio', 'nederland',
      'orange', 'vidor', 'silsbee', 'socorro', 'horizon city', 'fabens',
      'wolfforth', 'levelland', 'brownfield', 'pampa', 'borger', 'hereford',
      'dumas', 'andrews', 'pecos', 'fort stockton', 'alpine', 'monahans',
      'whitehouse', 'lindale', 'kilgore', 'henderson', 'jacksonville', 'athens',
      'hewitt', 'woodway', 'robinson', 'mcgregor', 'gatesville', 'salado',
      'navasota', 'madisonville', 'crockett', 'palestine', 'mount pleasant',
      'sulphur springs', 'greenville', 'commerce', 'bonham', 'gainesville',
      'burkburnett', 'iowa park', 'vernon', 'graham', 'mineral wells', 'weatherford',
      'granbury', 'stephenville', 'cleburne', 'joshua', 'alvarado', 'glen rose',
    ]),
    gov: GOV('TX'),
    statewide: [
      'indoor pickleball facilities Texas directory',
      'USTA Texas indoor tennis facilities',
      'indoor sports complex Texas list',
      'Texas volleyball clubs indoor facility list',
      'Texas badminton clubs list',
      'indoor padel clubs Texas',
      'best indoor pickleball courts Texas',
      'sportsplex Texas',
      'Texas YMCA gymnasium court rental',
      'indoor basketball facility Texas list',
    ],
  },
  PA: {
    code: 'PA',
    name: 'Pennsylvania',
    stateRe: /(?:PA|Pennsylvania|Penn\.?)/,
    // Pennsylvania ZIPs run 15000-19699.
    zipRe: /\b(?:PA|Pennsylvania)\s+1[5-9]\d{3}\b/,
    zipBare: /^1[5-9]\d{3}$/,
    areaCodes: /\(?(215|223|267|272|412|445|484|570|582|610|717|724|814|835|878)\)?[)\s.-]{1,3}\d{3}[\s.-]?\d{4}/,
    mentionRe: /\b(?:Eastern|Western|Central) Pennsylvania\b|\bPennsylvania\b/i,
    markets: PA_MARKETS,
    majorMarkets: [
      'Philadelphia PA', 'Pittsburgh PA', 'Allentown PA', 'Bethlehem PA', 'Harrisburg PA',
      'Lancaster PA', 'York PA', 'Reading PA', 'Erie PA', 'Scranton PA', 'Wilkes-Barre PA',
      'State College PA', 'Bala Cynwyd PA', 'King of Prussia PA', 'Wayne PA', 'West Chester PA',
      'Doylestown PA', 'Media PA', 'Newtown PA', 'Exton PA', 'Norristown PA', 'Lansdale PA',
      'Monroeville PA', 'Cranberry Township PA', 'Wexford PA', 'Mount Lebanon PA',
      'Bethel Park PA', 'Greensburg PA', 'Hershey PA', 'Camp Hill PA', 'Mechanicsburg PA',
      'Easton PA', 'Stroudsburg PA', 'Altoona PA', 'Williamsport PA', 'Johnstown PA',
    ],
    places: placeSet(PA_MARKETS, [
      'wynnewood', 'narberth', 'gladwyne', 'haverford', 'radnor', 'devon', 'berwyn',
      'paoli', 'frazer', 'chesterbrook', 'audubon', 'collegeville', 'skippack',
      'harleysville', 'souderton', 'perkasie', 'sellersville', 'chalfont', 'warrington',
      'richboro', 'southampton', 'feasterville', 'trevose', 'morrisville', 'fairless hills',
      'ridley park', 'swarthmore', 'wallingford', 'newtown square', 'glen mills',
      'garnet valley', 'aston', 'brookhaven', 'folsom', 'lansdowne', 'upper darby',
      'bristol', 'croydon', 'bensalem township', 'holland', 'churchville',
      'macungie', 'trexlertown', 'breinigsville', 'catasauqua', 'northampton',
      'palmerton', 'lehighton', 'jim thorpe', 'tannersville', 'bartonsville',
      'new cumberland', 'enola', 'marysville', 'dillsburg', 'etters', 'wormleysburg',
      'manheim', 'mount joy', 'strasburg', 'willow street', 'quarryville', 'denver',
      'shrewsbury', 'stewartstown', 'spring grove', 'east berlin', 'new oxford',
      'mohnton', 'shillington', 'kutztown', 'fleetwood', 'birdsboro', 'exeter',
      'mccandless', 'ross township', 'shaler', 'fox chapel', 'oakmont', 'plum',
      'penn hills', 'north huntingdon', 'irwin', 'jeannette', 'export', 'delmont',
      'peters township', 'venetia', 'bridgeville', 'carnegie', 'coraopolis',
      'imperial', 'mars', 'zelienople', 'evans city', 'gibsonia', 'allison park',
      'moosic', 'old forge', 'taylor', 'archbald', 'jessup', 'olyphant',
      'plains', 'exeter township', 'west pittston', 'shavertown', 'dallas',
      'edinboro', 'girard', 'north east', 'fairview', 'harborcreek', 'waterford',
      'boalsburg', 'port matilda', 'philipsburg', 'clearfield', 'punxsutawney',
      'montoursville', 'muncy', 'jersey shore', 'south williamsport', 'berwick',
      'shamokin', 'mount carmel', 'milton', 'watsontown', 'mifflinburg',
    ]),
    gov: GOV('PA'),
    statewide: [
      'indoor pickleball facilities Pennsylvania directory',
      'USTA Middle States indoor tennis facilities',
      'indoor sports complex Pennsylvania list',
      'Pennsylvania volleyball clubs indoor facility list',
      'Pennsylvania squash clubs list',
      'indoor padel clubs Pennsylvania',
      'best indoor pickleball courts Pennsylvania',
      'sportsplex Pennsylvania',
      'Pennsylvania YMCA gymnasium court rental',
      'indoor basketball facility Pennsylvania list',
    ],
  },
  MI: {
    code: 'MI',
    name: 'Michigan',
    stateRe: /(?:MI|Michigan|Mich\.?)/,
    // Michigan ZIPs run 48000-49999.
    zipRe: /\b(?:MI|Michigan)\s+4[89]\d{3}\b/,
    zipBare: /^4[89]\d{3}$/,
    areaCodes: /\(?(231|248|269|313|517|586|616|679|734|810|906|947|989)\)?[)\s.-]{1,3}\d{3}[\s.-]?\d{4}/,
    mentionRe: /\b(?:West|Southeast|Northern) Michigan\b|\bMichigan\b/i,
    markets: MI_MARKETS,
    majorMarkets: [
      'Detroit MI', 'Ann Arbor MI', 'Grand Rapids MI', 'Lansing MI', 'East Lansing MI',
      'Kalamazoo MI', 'Flint MI', 'Novi MI', 'Troy MI', 'Livonia MI', 'Canton MI',
      'Rochester Hills MI', 'Sterling Heights MI', 'Warren MI', 'Southfield MI',
      'Farmington Hills MI', 'Royal Oak MI', 'Birmingham MI', 'Northville MI',
      'Plymouth MI', 'Brighton MI', 'Holland MI', 'Portage MI', 'Traverse City MI',
      'Saginaw MI', 'Midland MI', 'Bay City MI', 'Muskegon MI', 'Jackson MI',
      'Battle Creek MI', 'Wyoming MI', 'Kentwood MI', 'Auburn Hills MI', 'Ypsilanti MI',
    ],
    places: placeSet(MI_MARKETS, [
      'berkley', 'ferndale', 'oak park', 'huntington woods', 'pleasant ridge',
      'beverly hills', 'franklin', 'orchard lake', 'keego harbor', 'walled lake',
      'white lake', 'highland', 'hartland', 'new hudson', 'lyon township',
      'redford', 'garden city', 'inkster', 'romulus', 'belleville', 'van buren',
      'allen park', 'lincoln park', 'southgate', 'riverview', 'woodhaven',
      'grosse ile', 'flat rock', 'rockwood', 'utica', 'washington township',
      'romeo', 'armada', 'richmond', 'new baltimore', 'harrison township',
      'roseville', 'eastpointe', 'fraser', 'center line', 'madison heights',
      'hamburg', 'pinckney', 'whitmore lake', 'milan', 'manchester',
      'haslett', 'williamston', 'mason', 'dewitt', 'st johns', 'charlotte',
      'comstock park', 'belmont', 'lowell', 'ionia', 'greenville', 'sparta',
      'coopersville', 'spring lake', 'fruitport', 'whitehall', 'montague',
      'mattawan', 'paw paw', 'plainwell', 'otsego', 'richland', 'vicksburg',
      'stevensville', 'bridgman', 'buchanan', 'dowagiac', 'edwardsburg',
      'grand ledge', 'eaton rapids', 'chelsea village', 'saline township',
      'burton', 'flushing', 'swartz creek', 'linden', 'goodrich', 'clio',
      'frankenmuth', 'saginaw township', 'freeland', 'auburn', 'essexville',
      'shepherd', 'ithaca', 'st louis', 'clare', 'harrison',
      'acme', 'williamsburg', 'suttons bay', 'elk rapids', 'kalkaska',
      'boyne city', 'east jordan', 'harbor springs', 'cheboygan', 'grayling',
      'negaunee', 'ishpeming', 'gladstone', 'menominee', 'calumet', 'hancock',
    ]),
    gov: GOV('MI'),
    statewide: [
      'indoor pickleball facilities Michigan directory',
      'USTA Midwest indoor tennis facilities Michigan',
      'indoor sports complex Michigan list',
      'Michigan volleyball clubs indoor facility list',
      'indoor padel clubs Michigan',
      'best indoor pickleball courts Michigan',
      'sportsplex Michigan',
      'Michigan YMCA gymnasium court rental',
      'indoor basketball facility Michigan list',
    ],
  },
  WA: {
    code: 'WA',
    name: 'Washington',
    stateRe: /(?:WA|Washington)/,
    // Washington ZIPs run 98001-99403.
    zipRe: /\b(?:WA|Washington)\s+(?:98\d{3}|99[0-4]\d{2})\b/,
    zipBare: /^(?:98\d{3}|99[0-4]\d{2})$/,
    areaCodes: /\(?(206|253|360|425|509|564)\)?[)\s.-]{1,3}\d{3}[\s.-]?\d{4}/,
    mentionRe: /\b(?:Eastern|Western) Washington\b|\bWashington State\b/i,
    markets: WA_MARKETS,
    places: placeSet(WA_MARKETS, [
      'ballard', 'fremont', 'wallingford', 'green lake', 'queen anne', 'magnolia',
      'capitol hill', 'university district', 'west seattle', 'columbia city',
      'rainier valley', 'georgetown', 'sodo', 'beacon hill', 'ravenna', 'wedgwood',
      'lake city', 'northgate', 'crown hill', 'phinney ridge', 'madison park',
      'leschi', 'madrona', 'newcastle', 'clyde hill', 'medina', 'hunts point',
      'yarrow point', 'factoria', 'eastgate', 'juanita', 'finn hill', 'totem lake',
      'bryn mawr', 'skyway', 'white center', 'boulevard park', 'east renton',
      'fairwood', 'panther lake', 'lea hill', 'algona', 'pacific',
      'parkland', 'spanaway', 'frederickson', 'graham', 'summit view', 'south hill',
      'edgewood', 'milton', 'dupont', 'steilacoom', 'lakebay', 'key peninsula',
      'east olympia', 'nisqually', 'rainier', 'bucoda', 'napavine',
      'winlock', 'toledo', 'castle rock', 'woodland', 'ridgefield', 'la center',
      'brush prairie', 'hazel dell', 'salmon creek', 'orchards', 'felida',
      'lake stevens', 'granite falls', 'darrington', 'sultan', 'gold bar',
      'index', 'startup', 'clearview', 'silver firs', 'mill creek east',
      'lynnwood south', 'meadowdale', 'esperance', 'picnic point',
      'freeland', 'langley', 'clinton', 'coupeville', 'friday harbor', 'lopez island',
      'orcas island', 'la conner', 'stanwood', 'camano island',
      'sunnyside', 'grandview', 'toppenish', 'zillah', 'wapato', 'selah', 'naches',
      'quincy', 'ephrata', 'soap lake', 'george', 'royal city', 'othello',
      'grand coulee', 'chelan', 'leavenworth', 'cashmere', 'peshastin',
      'cle elum', 'roslyn', 'college place', 'milton-freewater', 'dayton wa',
      'omak', 'okanogan', 'oroville', 'tonasket', 'republic', 'colfax',
      'palouse', 'clarkston', 'deer park', 'chewelah', 'kettle falls', 'usk',
      'medical lake', 'fairwood spokane', 'mead', 'otis orchards',
    ]),
    gov: GOV('WA'),
    statewide: [
      'indoor pickleball facilities Washington State directory',
      'USTA Pacific Northwest indoor tennis facilities Washington',
      'indoor sports complex Washington State list',
      'Washington State volleyball clubs indoor facility list',
      'indoor padel clubs Washington State',
      'best indoor pickleball courts Washington State',
      'sportsplex Washington State',
      'Washington State YMCA gymnasium court rental',
      'indoor basketball facility Washington State list',
    ],
  },
  AZ: {
    code: 'AZ',
    name: 'Arizona',
    stateRe: /(?:AZ|Arizona)/,
    // Arizona ZIPs run 85001-86556.
    zipRe: /\b(?:AZ|Arizona)\s+8[56]\d{3}\b/,
    zipBare: /^8[56]\d{3}$/,
    areaCodes: /\(?(480|520|602|623|928)\)?[)\s.-]{1,3}\d{3}[\s.-]?\d{4}/,
    mentionRe: /\bArizona\b/i,
    markets: AZ_MARKETS,
    places: placeSet(AZ_MARKETS, [
      'arcadia', 'biltmore', 'north central phoenix', 'north scottsdale',
      'old town scottsdale', 'south scottsdale', 'south mountain', 'moon valley',
      'deer valley', 'desert ridge', 'north gateway', 'estrella', 'rancho san marcos',
      'sun lakes', 'gold canyon', 'superstition mountain', 'san tan valley',
      'red rock', 'catalina', 'tanque verde', 'foothills tucson', 'rita ranch',
      'midvale park', 'flowing wells', 'casas adobes', 'tortolita', 'saddlebrooke',
      'picture rocks', 'three points', 'sierra vista southeast', 'hereford',
      'huachuca city', 'bisbee', 'tombstone', 'willcox', 'san manuel', 'oracle',
      'catalina foothills', 'coolidge', 'stanfield', 'arizona city', 'red rock az',
      'gila bend', 'ajo', 'why', 'wellton', 'somerton', 'san luis', 'dateland',
      'salome', 'quartzsite', 'parker', 'ehrenberg', 'topock', 'golden valley',
      'valle vista', 'meadview', 'dolan springs', 'kingman city', 'north kingman',
      'chino valley north', 'paulden', 'seligman', 'ash fork', 'clarkdale',
      'jerome', 'cornville', 'rimrock', 'lake montezuma', 'happy jack',
      'pine az', 'strawberry', 'star valley', 'pinetop-lakeside', 'snowflake',
      'taylor az', 'joseph city', 'heber-overgaard', 'concho', 'st johns',
      'springerville', 'eagar', 'alpine az', 'chinle', 'window rock', 'ganado',
      'tuba city', 'kayenta', 'lake havasu east', 'fortuna foothills', 'yuma foothills',
    ]),
    gov: GOV('AZ'),
    statewide: [
      'indoor pickleball facilities Arizona directory',
      'USTA Southwest indoor tennis facilities Arizona',
      'indoor sports complex Arizona list',
      'Arizona volleyball clubs indoor facility list',
      'indoor padel clubs Arizona',
      'best indoor pickleball courts Arizona',
      'sportsplex Arizona',
      'Arizona YMCA gymnasium court rental',
      'indoor basketball facility Arizona list',
    ],
  },
  NV: {
    code: 'NV',
    name: 'Nevada',
    stateRe: /(?:NV|Nevada)/,
    // Nevada ZIPs run 88901-89883.
    zipRe: /\b(?:NV|Nevada)\s+(?:889\d{2}|89\d{3})\b/,
    zipBare: /^(?:889\d{2}|89\d{3})$/,
    areaCodes: /\(?(702|725|775)\)?[)\s.-]{1,3}\d{3}[\s.-]?\d{4}/,
    mentionRe: /\bNevada\b/i,
    markets: NV_MARKETS,
    places: placeSet(NV_MARKETS, [
      'summerlin south', 'summerlin north', 'the lakes', 'centennial hills',
      'aliante', 'north valleys', 'spring valley south', 'southern highlands',
      'seven hills', 'green valley', 'anthem henderson', 'whitney nv',
      'winchester nv', 'sunrise nv', 'nellis afb', 'blue diamond nv',
      'indian springs', 'moapa valley', 'overton nv', 'logandale', 'searchlight',
      'goodsprings', 'jean nv', 'primm', 'cal-nev-ari', 'sandy valley',
      'stagecoach nv', 'silver springs', 'wellington nv', 'smith valley',
      'topaz ranch estates', 'zephyr cove', 'stateline nv', 'genoa nv',
      'washoe valley', 'sun valley nv', 'spanish springs', 'cold springs nv',
      'verdi', 'truckee meadows', 'pyramid lake', 'wadsworth nv', 'lovelock',
      'gerlach', 'lamoille', 'spring creek nv', 'wells nv', 'jackpot nv',
      'west wendover', 'carlin', 'eureka nv', 'austin nv', 'hawthorne nv',
      'schurz', 'gabbs', 'caliente nv', 'panaca', 'alamo nv', 'beatty nv',
      'amargosa valley', 'indian hills nv', 'johnson lane', 'ruhenstroth',
    ]),
    gov: GOV('NV'),
    statewide: [
      'indoor pickleball facilities Nevada directory',
      'USTA Intermountain indoor tennis facilities Nevada',
      'indoor sports complex Nevada list',
      'Nevada volleyball clubs indoor facility list',
      'best indoor pickleball courts Nevada',
      'sportsplex Nevada',
      'Nevada YMCA gymnasium court rental',
    ],
  },
  OR: {
    code: 'OR',
    name: 'Oregon',
    stateRe: /(?:OR|Oregon)/,
    // Oregon ZIPs run 97001-97920.
    zipRe: /\b(?:OR|Oregon)\s+97\d{3}\b/,
    zipBare: /^97\d{3}$/,
    areaCodes: /\(?(458|503|541|971)\)?[)\s.-]{1,3}\d{3}[\s.-]?\d{4}/,
    mentionRe: /\bOregon\b/i,
    markets: OR_MARKETS,
    places: placeSet(OR_MARKETS, [
      'pearl district', 'northwest portland', 'sellwood', 'st johns portland',
      'hollywood district', 'hawthorne', 'belmont', 'lents', 'montavilla',
      'cully', 'parkrose', 'centennial portland', 'cedar mill', 'bethany',
      'aloha', 'garden home', 'raleigh hills', 'metzger', 'tanasbourne',
      'orenco', 'north plains', 'gaston', 'banks', 'scholls', 'sherwood south',
      'tualatin valley', 'stafford', 'mulino', 'colton or', 'gladstone',
      'boring', 'gresham east', 'fairview or', 'corbett', 'bridal veil',
      'cascade locks', 'rockaway beach', 'wheeler', 'nehalem', 'manzanita',
      'garibaldi', 'bay city or', 'netarts', 'oceanside or', 'pacific city',
      'lincoln beach', 'depoe bay', 'gleneden beach', 'waldport', 'yachats',
      'reedsport', 'winston', 'myrtle creek', 'canyonville', 'glide',
      'sutherlin', 'oakland or', 'drain', 'yoncalla', 'creswell', 'coburg',
      'harrisburg or', 'halsey', 'brownsville or', 'scio', 'jefferson or',
      'turner', 'aumsville', 'sublimity', 'mount angel', 'gervais',
      'st paul or', 'carlton', 'lafayette or', 'dundee', 'sherwood forest',
      'wilsonville south', 'gold hill', 'rogue river or', 'shady cove',
      'jacksonville or', 'eagle point', 'white city', 'winston or', 'yreka',
      'chiloquin', 'chemult', 'crescent or', 'la pine', 'sunriver',
      'terrebonne', 'tumalo', 'culver or', 'madras', 'the dalles east',
      'hermiston', 'stanfield', 'boardman or', 'irrigon', 'umatilla',
      'milton-freewater', 'enterprise or', 'joseph or', 'wallowa', 'union or',
      'elgin or', 'north powder', 'baker city east', 'huntington or',
      'nyssa', 'vale or', 'burns', 'lakeview or', 'christmas valley',
    ]),
    gov: GOV('OR'),
    statewide: [
      'indoor pickleball facilities Oregon directory',
      'USTA Pacific Northwest indoor tennis facilities Oregon',
      'indoor sports complex Oregon list',
      'Oregon volleyball clubs indoor facility list',
      'indoor padel clubs Oregon',
      'best indoor pickleball courts Oregon',
      'sportsplex Oregon',
      'Oregon YMCA gymnasium court rental',
    ],
  },
};

export function stateConfig(code) {
  const s = STATES[String(code || '').toUpperCase()];
  if (!s) throw new Error(`Unknown state "${code}". Add it to src/states.js.`);
  return s;
}
